"""Deprecate Old Product Fields

Revision ID: 0488a8941877
Revises: 238dff73eb17
Create Date: 2021-12-03 06:39:39.663348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0488a8941877'
down_revision = '238dff73eb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_price', table_name='product')
    op.drop_column('product', 'wallet')
    op.drop_column('product', 'currency')
    op.drop_column('product', 'stake_limit')
    op.drop_column('product', 'chain')
    op.drop_column('product', 'price')
    op.drop_column('product', 'is_on_platform')
    op.drop_column('product', 'mode')
    op.drop_column('product', 'third_party_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('third_party_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('is_on_platform', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('chain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('stake_limit', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('currency', sa.VARCHAR(), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('wallet', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_product_price', 'product', ['price'], unique=False)
    # ### end Alembic commands ###
