"""Add Encryption Product Property

Revision ID: 1386741fb433
Revises: 7210171b41e1
Create Date: 2022-01-20 12:50:17.789429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1386741fb433'
down_revision = '7210171b41e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('use_encryption', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'use_encryption')
    # ### end Alembic commands ###
