"""Crypto Support

Revision ID: 1b87f6a5cf85
Revises: 7ddf2372a420
Create Date: 2021-08-31 06:50:26.628091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b87f6a5cf85'
down_revision = '7ddf2372a420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_order', sa.DateTime(), nullable=False),
    sa.Column('round_order', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('to_address', sa.String(), nullable=True),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_date_order'), 'order', ['date_order'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.add_column('product', sa.Column('is_on_platform', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('product', sa.Column('currency', sa.String(), server_default='USD', nullable=False))
    op.add_column('product', sa.Column('chain', sa.String(), nullable=True))
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('product', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('product', 'chain')
    op.drop_column('product', 'currency')
    op.drop_column('product', 'is_on_platform')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_date_order'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
