"""Add User Last Sync Date

Revision ID: 1d2a044a16eb
Revises: 73cce7709e29
Create Date: 2022-04-10 11:35:35.869792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2a044a16eb'
down_revision = '73cce7709e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_last_numerai_sync', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_last_numerai_sync')
    # ### end Alembic commands ###
