"""Add Daily Option to Product

Revision ID: 205e12d72c7d
Revises: 9e25f4a96b9a
Create Date: 2022-12-04 14:09:08.980897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205e12d72c7d'
down_revision = '9e25f4a96b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_daily', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_daily')
    # ### end Alembic commands ###
