"""Add Voting

Revision ID: 238dff73eb17
Revises: 78477dc7bb95
Create Date: 2021-11-21 02:25:08.401934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238dff73eb17'
down_revision = '78477dc7bb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_finish', sa.DateTime(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('options', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('is_multiple', sa.Boolean(), nullable=True),
    sa.Column('max_options', sa.Integer(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('is_blind', sa.Boolean(), nullable=True),
    sa.Column('weight_mode', sa.String(), nullable=True),
    sa.Column('is_stake_predetermined', sa.Boolean(), nullable=True),
    sa.Column('min_stake', sa.Numeric(), nullable=True),
    sa.Column('min_rounds', sa.Integer(), nullable=True),
    sa.Column('clip_low', sa.Numeric(), nullable=True),
    sa.Column('clip_high', sa.Numeric(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_date_creation'), 'poll', ['date_creation'], unique=False)
    op.create_index(op.f('ix_poll_date_finish'), 'poll', ['date_finish'], unique=False)
    op.create_index(op.f('ix_poll_description'), 'poll', ['description'], unique=False)
    op.create_index(op.f('ix_poll_id'), 'poll', ['id'], unique=False)
    op.create_index(op.f('ix_poll_topic'), 'poll', ['topic'], unique=False)
    op.create_table('stake_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tournament', sa.Integer(), nullable=False),
    sa.Column('nmr_staked', sa.Numeric(), nullable=True),
    sa.Column('return_13_weeks', sa.Numeric(), nullable=True),
    sa.Column('return_52_weeks', sa.Numeric(), nullable=True),
    sa.Column('payout_pending', sa.Numeric(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stake_snapshot_date_creation'), 'stake_snapshot', ['date_creation'], unique=False)
    op.create_index(op.f('ix_stake_snapshot_id'), 'stake_snapshot', ['id'], unique=False)
    op.create_index(op.f('ix_stake_snapshot_name'), 'stake_snapshot', ['name'], unique=False)
    op.create_index(op.f('ix_stake_snapshot_tournament'), 'stake_snapshot', ['tournament'], unique=False)
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_vote', sa.DateTime(), nullable=False),
    sa.Column('option', sa.Integer(), nullable=False),
    sa.Column('weight_basis', sa.Numeric(), nullable=True),
    sa.Column('voter_id', sa.String(), nullable=False),
    sa.Column('voter_address', sa.String(), nullable=True),
    sa.Column('poll_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'voter_id', 'option', name='uix_vote_poll_voter_option')
    )
    op.create_index(op.f('ix_vote_date_vote'), 'vote', ['date_vote'], unique=False)
    op.create_index(op.f('ix_vote_id'), 'vote', ['id'], unique=False)
    op.create_index(op.f('ix_vote_option'), 'vote', ['option'], unique=False)
    op.create_index(op.f('ix_vote_voter_id'), 'vote', ['voter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_voter_id'), table_name='vote')
    op.drop_index(op.f('ix_vote_option'), table_name='vote')
    op.drop_index(op.f('ix_vote_id'), table_name='vote')
    op.drop_index(op.f('ix_vote_date_vote'), table_name='vote')
    op.drop_table('vote')
    op.drop_index(op.f('ix_stake_snapshot_tournament'), table_name='stake_snapshot')
    op.drop_index(op.f('ix_stake_snapshot_name'), table_name='stake_snapshot')
    op.drop_index(op.f('ix_stake_snapshot_id'), table_name='stake_snapshot')
    op.drop_index(op.f('ix_stake_snapshot_date_creation'), table_name='stake_snapshot')
    op.drop_table('stake_snapshot')
    op.drop_index(op.f('ix_poll_topic'), table_name='poll')
    op.drop_index(op.f('ix_poll_id'), table_name='poll')
    op.drop_index(op.f('ix_poll_description'), table_name='poll')
    op.drop_index(op.f('ix_poll_date_finish'), table_name='poll')
    op.drop_index(op.f('ix_poll_date_creation'), table_name='poll')
    op.drop_table('poll')
    # ### end Alembic commands ###
