"""Modify Order Transaction

Revision ID: 3554967bf4ab
Revises: 0488a8941877
Create Date: 2021-12-04 08:33:55.157765

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '3554967bf4ab'
down_revision = '0488a8941877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_order_transaction_hash'), 'order', ['transaction_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_transaction_hash'), table_name='order')
    # ### end Alembic commands ###
