"""Add Stake Mode

Revision ID: 3c166804c87f
Revises: 7c218fac202f
Create Date: 2021-10-01 05:20:21.414976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c166804c87f'
down_revision = '7c218fac202f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('mode', sa.String(), server_default='file', nullable=False))
    op.add_column('order', sa.Column('stake_limit', sa.Numeric(), nullable=True))
    op.add_column('order', sa.Column('submit_model_id', sa.String(), nullable=True))
    op.add_column('order', sa.Column('submit_model_name', sa.String(), nullable=True))
    op.add_column('order', sa.Column('submit_state', sa.String(), nullable=True))
    op.add_column('product', sa.Column('mode', sa.String(), nullable=True))
    op.add_column('product', sa.Column('stake_limit', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'stake_limit')
    op.drop_column('product', 'mode')
    op.drop_column('order', 'submit_state')
    op.drop_column('order', 'submit_model_name')
    op.drop_column('order', 'submit_model_id')
    op.drop_column('order', 'stake_limit')
    op.drop_column('order', 'mode')
    # ### end Alembic commands ###
