"""Add Product Delivery Counter

Revision ID: 40668f3c9788
Revises: dc03a133ce4f
Create Date: 2022-04-23 01:52:07.708974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40668f3c9788'
down_revision = 'dc03a133ce4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('total_qty_sales', sa.Integer(), server_default='0', nullable=True))
    op.add_column('product', sa.Column('total_qty_delivered', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'total_qty_delivered')
    op.drop_column('product', 'total_qty_sales')
    # ### end Alembic commands ###
