"""Add props to user

Revision ID: 43cecbe71690
Revises: feec00cc99b2
Create Date: 2023-03-24 06:52:19.009641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cecbe71690'
down_revision = 'feec00cc99b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('props', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'props')
    # ### end Alembic commands ###
