"""Add Coupon

Revision ID: 474983073c61
Revises: d0a272545ecf
Create Date: 2021-12-18 12:36:06.132229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474983073c61'
down_revision = 'd0a272545ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('applicability', sa.String(), nullable=False),
    sa.Column('applicable_product_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('applicable_seller_id', sa.Integer(), nullable=True),
    sa.Column('min_spend', sa.Numeric(), nullable=True),
    sa.Column('max_discount', sa.Numeric(), nullable=True),
    sa.Column('discount_mode', sa.String(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('quantity_total', sa.Integer(), nullable=True),
    sa.Column('is_owned_by_seller', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_applicability'), 'coupon', ['applicability'], unique=False)
    op.create_index(op.f('ix_coupon_code'), 'coupon', ['code'], unique=False)
    op.create_index(op.f('ix_coupon_date_creation'), 'coupon', ['date_creation'], unique=False)
    op.create_index(op.f('ix_coupon_date_expiration'), 'coupon', ['date_expiration'], unique=False)
    op.create_index(op.f('ix_coupon_id'), 'coupon', ['id'], unique=False)
    op.create_index(op.f('ix_coupon_quantity_total'), 'coupon', ['quantity_total'], unique=False)
    op.create_index(op.f('ix_coupon_state'), 'coupon', ['state'], unique=False)
    op.add_column('order', sa.Column('coupon', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('coupon_specs', sa.JSON(), nullable=True))
    op.add_column('order', sa.Column('applied_coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key('order_applied_coupon_id_fkey', 'order', 'coupon', ['applied_coupon_id'], ['id'], ondelete='CASCADE')
    op.add_column('product_option', sa.Column('coupon', sa.Boolean(), nullable=True))
    op.add_column('product_option', sa.Column('coupon_specs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_option', 'coupon_specs')
    op.drop_column('product_option', 'coupon')
    op.drop_constraint('order_applied_coupon_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'applied_coupon_id')
    op.drop_column('order', 'coupon_specs')
    op.drop_column('order', 'coupon')
    op.drop_index(op.f('ix_coupon_state'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_quantity_total'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_id'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_date_expiration'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_date_creation'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_code'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_applicability'), table_name='coupon')
    op.drop_table('coupon')
    # ### end Alembic commands ###
