"""Add Quantity Sales Global Stats

Revision ID: 47d1c356710b
Revises: 40668f3c9788
Create Date: 2022-04-28 12:54:58.942138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d1c356710b'
down_revision = '40668f3c9788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('globals', sa.Column('total_qty_sales', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('globals', 'total_qty_sales')
    # ### end Alembic commands ###
