"""Add Product Expiration

Revision ID: 4e214fdd8879
Revises: 245241d21665
Create Date: 2021-09-03 13:54:28.646532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e214fdd8879'
down_revision = '245241d21665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_active', sa.Boolean(), server_default='t', nullable=True))
    op.add_column('product', sa.Column('expiration_round', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'expiration_round')
    op.drop_column('product', 'is_active')
    # ### end Alembic commands ###
