"""Add Product Sales Stats

Revision ID: 56a72fdc2de5
Revises: ab1fd8ee0c92
Create Date: 2021-10-03 10:12:24.590092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a72fdc2de5'
down_revision = 'ab1fd8ee0c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('total_num_sales', sa.Integer(), server_default='0', nullable=True))
    op.add_column('product', sa.Column('last_sale_price', sa.Numeric(), nullable=True))
    op.add_column('product', sa.Column('last_sale_price_delta', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'last_sale_price_delta')
    op.drop_column('product', 'last_sale_price')
    op.drop_column('product', 'total_num_sales')
    # ### end Alembic commands ###
