"""Add Artifact State

Revision ID: 58e5c7e048ac
Revises: d8ad2f6b66a9
Create Date: 2021-10-13 08:33:49.794819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e5c7e048ac'
down_revision = 'd8ad2f6b66a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact', sa.Column('state', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifact', 'state')
    # ### end Alembic commands ###
