"""Add Order Artifact Numerai Direct Flag

Revision ID: 6506d86fa60b
Revises: 1386741fb433
Create Date: 2022-01-30 07:39:57.634787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6506d86fa60b'
down_revision = '1386741fb433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_artifact', sa.Column('is_numerai_direct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_artifact', 'is_numerai_direct')
    # ### end Alembic commands ###
