"""Add User Socials

Revision ID: 71bb4bab3ce2
Revises: 1d2a044a16eb
Create Date: 2022-04-14 12:18:53.089657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bb4bab3ce2'
down_revision = '1d2a044a16eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_rocketchat', sa.String(), nullable=True))
    op.add_column('user', sa.Column('social_linkedin', sa.String(), nullable=True))
    op.add_column('user', sa.Column('social_twitter', sa.String(), nullable=True))
    op.add_column('user', sa.Column('social_website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'social_website')
    op.drop_column('user', 'social_twitter')
    op.drop_column('user', 'social_linkedin')
    op.drop_column('user', 'social_rocketchat')
    # ### end Alembic commands ###
