"""Add Order Artifact

Revision ID: 7210171b41e1
Revises: 86c33f5ebf9b
Create Date: 2022-01-20 12:34:34.934904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7210171b41e1'
down_revision = '86c33f5ebf9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_artifact',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('round_tournament', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('object_name', sa.String(), nullable=True),
    sa.Column('object_size', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), server_default='pending', nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_artifact_date'), 'order_artifact', ['date'], unique=False)
    op.create_index(op.f('ix_order_artifact_id'), 'order_artifact', ['id'], unique=False)
    op.create_index(op.f('ix_order_artifact_object_name'), 'order_artifact', ['object_name'], unique=False)
    op.create_index(op.f('ix_order_artifact_round_tournament'), 'order_artifact', ['round_tournament'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_artifact_round_tournament'), table_name='order_artifact')
    op.drop_index(op.f('ix_order_artifact_object_name'), table_name='order_artifact')
    op.drop_index(op.f('ix_order_artifact_id'), table_name='order_artifact')
    op.drop_index(op.f('ix_order_artifact_date'), table_name='order_artifact')
    op.drop_table('order_artifact')
    # ### end Alembic commands ###
