"""Add Numerai Models

Revision ID: 76140d7db1d2
Revises: 85b3d8acbe08
Create Date: 2021-08-22 12:51:55.480289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76140d7db1d2'
down_revision = '85b3d8acbe08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tournament', sa.Integer(), nullable=True),
    sa.Column('nmr_staked', sa.Numeric(), nullable=True),
    sa.Column('latest_ranks', sa.JSON(), nullable=True),
    sa.Column('latest_reps', sa.JSON(), nullable=True),
    sa.Column('latest_returns', sa.JSON(), nullable=True),
    sa.Column('round_model_performances', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_id'), 'model', ['id'], unique=False)
    op.create_index(op.f('ix_model_name'), 'model', ['name'], unique=False)
    op.add_column('product', sa.Column('model_id', sa.String(), nullable=True))
    op.create_foreign_key('product_model_id_fkey', 'product', 'model', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_model_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'model_id')
    op.drop_index(op.f('ix_model_name'), table_name='model')
    op.drop_index(op.f('ix_model_id'), table_name='model')
    op.drop_table('model')
    # ### end Alembic commands ###
