"""Add Round Rollover Global State

Revision ID: 7c218fac202f
Revises: 89733315e30b
Create Date: 2021-09-24 13:18:31.266595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c218fac202f'
down_revision = '89733315e30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('globals', sa.Column('is_doing_round_rollover', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('globals', 'is_doing_round_rollover')
    # ### end Alembic commands ###
