"""Add last order reminder date

Revision ID: 84865aba07e9
Revises: d0a8474d98a1
Create Date: 2022-07-28 07:08:18.275923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84865aba07e9'
down_revision = 'd0a8474d98a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('last_reminder_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'last_reminder_date')
    # ### end Alembic commands ###
