"""Make product sku unique

Revision ID: 85b3d8acbe08
Revises: 8d829888d1bf
Create Date: 2021-08-14 06:07:17.572721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b3d8acbe08'
down_revision = '8d829888d1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_sku', table_name='product')
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.create_index('ix_product_sku', 'product', ['sku'], unique=False)
    # ### end Alembic commands ###
