"""Add Encryption Key

Revision ID: 86c33f5ebf9b
Revises: 06bf219bcb57
Create Date: 2022-01-20 07:42:07.339098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c33f5ebf9b'
down_revision = '06bf219bcb57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('buyer_public_key', sa.String(), nullable=True))
    op.add_column('user', sa.Column('public_key', sa.String(), nullable=True))
    op.add_column('user', sa.Column('encrypted_private_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'encrypted_private_key')
    op.drop_column('user', 'public_key')
    op.drop_column('order', 'buyer_public_key')
    # ### end Alembic commands ###
