"""Add Category Round Indicator

Revision ID: 89733315e30b
Revises: a4805e5f9c43
Create Date: 2021-09-18 12:26:07.691986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89733315e30b'
down_revision = 'a4805e5f9c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_per_round', sa.Boolean(), server_default='t', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_per_round')
    # ### end Alembic commands ###
