"""Deprecate Unused Coupon Seller Field

Revision ID: 973921226c02
Revises: c15371ebe3ce
Create Date: 2022-05-15 07:40:49.582401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973921226c02'
down_revision = 'c15371ebe3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'applicable_seller_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('applicable_seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
