"""Add Product Review

Revision ID: 9a5f837c23e2
Revises: 5536b5b72c9b
Create Date: 2021-10-15 08:53:56.997127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5f837c23e2'
down_revision = '5536b5b72c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('round_tournament', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('is_verified_order', sa.Boolean(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_created_at'), 'review', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.create_index(op.f('ix_review_rating'), 'review', ['rating'], unique=False)
    op.create_index(op.f('ix_review_round_tournament'), 'review', ['round_tournament'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_round_tournament'), table_name='review')
    op.drop_index(op.f('ix_review_rating'), table_name='review')
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_index(op.f('ix_review_created_at'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
