"""Add Order Rounds and Props

Revision ID: 9e25f4a96b9a
Revises: ff636cecf5ff
Create Date: 2022-12-02 08:20:41.111397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e25f4a96b9a'
down_revision = 'ff636cecf5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('rounds', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('order', sa.Column('props', sa.JSON(), nullable=True))
    op.alter_column('order', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_column('order', 'props')
    op.drop_column('order', 'rounds')
    # ### end Alembic commands ###
