"""Make User Numerai Wallet Unique

Revision ID: a4805e5f9c43
Revises: fd613cc088e8
Create Date: 2021-09-17 13:30:34.804562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4805e5f9c43'
down_revision = 'fd613cc088e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['numerai_wallet_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
