"""Add Category Tournament Indicator

Revision ID: ab1fd8ee0c92
Revises: 3c166804c87f
Create Date: 2021-10-03 02:45:54.942744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1fd8ee0c92'
down_revision = '3c166804c87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('tournament', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_category_tournament'), 'category', ['tournament'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_tournament'), table_name='category')
    op.drop_column('category', 'tournament')
    # ### end Alembic commands ###
