"""Update Artifact

Revision ID: abdb034e9481
Revises: 08f1bb0eed37
Create Date: 2021-09-11 12:33:31.581373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdb034e9481'
down_revision = '08f1bb0eed37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact', sa.Column('object_name', sa.String(), nullable=True))
    op.add_column('artifact', sa.Column('object_size', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_artifact_object_name'), 'artifact', ['object_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_object_name'), table_name='artifact')
    op.drop_column('artifact', 'object_size')
    op.drop_column('artifact', 'object_name')
    # ### end Alembic commands ###
