"""Add product round lock

Revision ID: bcbca7b17c1d
Revises: 5eacb83fd25a
Create Date: 2023-05-27 13:17:11.747096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbca7b17c1d'
down_revision = '5eacb83fd25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('round_lock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'round_lock')
    # ### end Alembic commands ###
