"""Deprecate Unused Artifact Fields

Revision ID: c15371ebe3ce
Revises: ce37d2f64ea2
Create Date: 2022-05-15 05:28:25.119988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15371ebe3ce'
down_revision = 'ce37d2f64ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifact', 'url')
    op.drop_column('artifact', 'description')
    op.drop_column('order_artifact', 'url')
    op.drop_column('order_artifact', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_artifact', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order_artifact', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artifact', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artifact', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
