"""Add Voting

Revision ID: c8ed936cd0b9
Revises: 78477dc7bb95
Create Date: 2021-11-13 14:23:49.545865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ed936cd0b9'
down_revision = '78477dc7bb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_finish', sa.DateTime(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('options', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('is_multiple', sa.Boolean(), nullable=True),
    sa.Column('max_options', sa.Integer(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('is_blind', sa.Boolean(), nullable=True),
    sa.Column('is_numerai_only', sa.Boolean(), nullable=True),
    sa.Column('is_stake_predetermined', sa.Boolean(), nullable=True),
    sa.Column('weight_mode', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_date_creation'), 'poll', ['date_creation'], unique=False)
    op.create_index(op.f('ix_poll_date_finish'), 'poll', ['date_finish'], unique=False)
    op.create_index(op.f('ix_poll_description'), 'poll', ['description'], unique=False)
    op.create_index(op.f('ix_poll_id'), 'poll', ['id'], unique=False)
    op.create_index(op.f('ix_poll_topic'), 'poll', ['topic'], unique=False)
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_vote', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('voter_id', sa.String(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'voter_id', name='uix_vote_poll_voter')
    )
    op.create_index(op.f('ix_vote_date_vote'), 'vote', ['date_vote'], unique=False)
    op.create_index(op.f('ix_vote_id'), 'vote', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_id'), table_name='vote')
    op.drop_index(op.f('ix_vote_date_vote'), table_name='vote')
    op.drop_table('vote')
    op.drop_index(op.f('ix_poll_topic'), table_name='poll')
    op.drop_index(op.f('ix_poll_id'), table_name='poll')
    op.drop_index(op.f('ix_poll_description'), table_name='poll')
    op.drop_index(op.f('ix_poll_date_finish'), table_name='poll')
    op.drop_index(op.f('ix_poll_date_creation'), table_name='poll')
    op.drop_table('poll')
    # ### end Alembic commands ###
