"""Fix Coupon Cascade

Revision ID: c9184785fa1a
Revises: 973921226c02
Create Date: 2022-05-20 07:18:50.291915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9184785fa1a'
down_revision = '973921226c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_applied_coupon_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key('order_applied_coupon_id_fkey', 'order', 'coupon', ['applied_coupon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_applied_coupon_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key('order_applied_coupon_id_fkey', 'order', 'coupon', ['applied_coupon_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
