"""Add Coupon Creator Info

Revision ID: ce37d2f64ea2
Revises: 47d1c356710b
Create Date: 2022-05-12 01:03:19.853474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce37d2f64ea2'
down_revision = '47d1c356710b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coupon', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupon', type_='foreignkey')
    op.drop_column('coupon', 'creator_id')
    # ### end Alembic commands ###
