"""Add Stake Snapshot Time Travel

Revision ID: d0a272545ecf
Revises: 306195a7f16f
Create Date: 2021-12-10 08:27:10.460939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a272545ecf'
down_revision = '306195a7f16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('stake_basis_round', sa.Integer(), nullable=True))
    op.add_column('stake_snapshot', sa.Column('round_tournament', sa.Integer(), server_default='293', nullable=False))
    op.create_index(op.f('ix_stake_snapshot_round_tournament'), 'stake_snapshot', ['round_tournament'], unique=False)
    op.create_unique_constraint('uix_stake_snapshot_round_name_tournament', 'stake_snapshot', ['round_tournament', 'name', 'tournament'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_stake_snapshot_round_name_tournament', 'stake_snapshot', type_='unique')
    op.drop_index(op.f('ix_stake_snapshot_round_tournament'), table_name='stake_snapshot')
    op.drop_column('stake_snapshot', 'round_tournament')
    op.drop_column('poll', 'stake_basis_round')
    # ### end Alembic commands ###
