"""Add Category Submission Indicator

Revision ID: d8ad2f6b66a9
Revises: 56a72fdc2de5
Create Date: 2021-10-09 14:22:15.719617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ad2f6b66a9'
down_revision = '56a72fdc2de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_submission', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_submission')
    # ### end Alembic commands ###
