"""Add Category Model Indicator

Revision ID: dc03a133ce4f
Revises: 71bb4bab3ce2
Create Date: 2022-04-17 13:26:40.527674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc03a133ce4f'
down_revision = '71bb4bab3ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_per_model', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_per_model')
    # ### end Alembic commands ###
