"""Add Product Option

Revision ID: e74bf3e984cd
Revises: ee346caf6181
Create Date: 2021-10-27 07:02:17.339338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74bf3e984cd'
down_revision = 'ee346caf6181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_on_platform', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('third_party_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('wallet', sa.String(), nullable=True),
    sa.Column('chain', sa.String(), nullable=True),
    sa.Column('stake_limit', sa.Numeric(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_option_id'), 'product_option', ['id'], unique=False)
    op.create_index(op.f('ix_product_option_price'), 'product_option', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_option_price'), table_name='product_option')
    op.drop_index(op.f('ix_product_option_id'), table_name='product_option')
    op.drop_table('product_option')
    # ### end Alembic commands ###
