"""Add Global Stats

Revision ID: ee346caf6181
Revises: 9a5f837c23e2
Create Date: 2021-10-16 12:32:43.042176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee346caf6181'
down_revision = '9a5f837c23e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('globals', sa.Column('total_num_products', sa.Integer(), nullable=True))
    op.add_column('globals', sa.Column('total_num_sales', sa.Integer(), nullable=True))
    op.add_column('globals', sa.Column('total_sales_nmr', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('globals', 'total_sales_nmr')
    op.drop_column('globals', 'total_num_sales')
    op.drop_column('globals', 'total_num_products')
    # ### end Alembic commands ###
