"""Add Encryption Key V2

Revision ID: efa4f2aaa77d
Revises: 84865aba07e9
Create Date: 2022-09-23 06:07:58.055434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa4f2aaa77d'
down_revision = '84865aba07e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_key_v2', sa.String(), nullable=True))
    op.add_column('user', sa.Column('encrypted_private_key_v2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'encrypted_private_key_v2')
    op.drop_column('user', 'public_key_v2')
    # ### end Alembic commands ###
