"""Deprecate Old Product

Revision ID: f08aee802614
Revises: e74bf3e984cd
Create Date: 2021-10-27 15:41:14.459187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08aee802614'
down_revision = 'e74bf3e984cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'is_on_platform',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('product', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('product', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('product', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('product', 'is_on_platform',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
