"""Add Featured Products

Revision ID: f484f9b8e59c
Revises: 474983073c61
Create Date: 2021-12-25 08:32:20.731305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f484f9b8e59c'
down_revision = '474983073c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('featured_products', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'featured_products')
    # ### end Alembic commands ###
