"""Update Product Wallet

Revision ID: fd613cc088e8
Revises: abdb034e9481
Create Date: 2021-09-17 12:00:56.550545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd613cc088e8'
down_revision = 'abdb034e9481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('wallet', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'wallet')
    # ### end Alembic commands ###
