"""Remove Deprecated Order Quantity Fields

Revision ID: feec00cc99b2
Revises: 205e12d72c7d
Create Date: 2022-12-14 14:19:33.414667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feec00cc99b2'
down_revision = '205e12d72c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'quantity')
    op.drop_column('order', 'round_order_end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('round_order_end', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
