"""Add order end round

Revision ID: ff636cecf5ff
Revises: efa4f2aaa77d
Create Date: 2022-10-22 05:02:07.760377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff636cecf5ff'
down_revision = 'efa4f2aaa77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('round_order_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'round_order_end')
    # ### end Alembic commands ###
