name: Run tests

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
      tags:
        description: 'Description'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'

  # backend jobs
  backend-test:
    name: Test Backend
    needs: changes
    # if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Pull the latest image to build, and avoid caching pull-only images.
      # (docker pull is faster than caching in most cases.)
      - name: Pull Docker Images
        run: |
          docker compose pull --quiet proxy db pgadmin queue flower
          docker pull --quiet python:3.7
          docker pull --quiet tiangolo/uvicorn-gunicorn-fastapi:python3.7
          docker pull --quiet node:14

      - name: Test backend
        run: sh ./scripts/test.sh
        env:
          GCP_STORAGE_BUCKET: storage.test.numerbay.ai
          GCP_SERVICE_ACCOUNT_INFO: ${{ secrets.APP_GCP_SERVICE_ACCOUNT_INFO }}
